definitions:
  handler.projectRegisterRequest:
    properties:
      project:
        properties:
          email:
            type: string
          name:
            type: string
          password:
            type: string
          token_address:
            type: string
        required:
        - email
        - name
        - password
        - token_address
        type: object
    type: object
  handler.projectResponse:
    properties:
      user:
        properties:
          bio:
            type: string
          email:
            type: string
          token:
            type: string
          username:
            type: string
        type: object
    type: object
  utils.Error:
    properties:
      errors:
        additionalProperties: true
        type: object
    type: object
info:
  contact: {}
paths:
  /project:
    post:
      consumes:
      - application/json
      description: Create a project
      operationId: create-project
      parameters:
      - description: Project to create made of text and media
        in: body
        name: project
        required: true
        schema:
          $ref: '#/definitions/handler.projectRegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handler.projectResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.Error'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/utils.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Error'
      security:
      - ApiKeyAuth: []
      summary: Create a project
      tags:
      - project
swagger: "2.0"
